
public static class PrefabPaths {

    public static readonly string[] treePaths = {
        "Prefabs/Nature Kit/tree_thin",
        "Prefabs/Nature Kit/tree_blocks_fall",
        "Prefabs/Nature Kit/tree_blocks",
        "Prefabs/Nature Kit/tree_cone_dark",
        "Prefabs/Nature Kit/tree_cone_fall",
        "Prefabs/Nature Kit/tree_cone",
        "Prefabs/Nature Kit/tree_default_dark",
        "Prefabs/Nature Kit/tree_default_fall",
        "Prefabs/Nature Kit/tree_default",
        "Prefabs/Nature Kit/tree_detailed_dark",
        "Prefabs/Nature Kit/tree_detailed_fall",
        "Prefabs/Nature Kit/tree_detailed",
        "Prefabs/Nature Kit/tree_fat_darkh",
        "Prefabs/Nature Kit/tree_fat_fall",
        "Prefabs/Nature Kit/tree_fat",
        "Prefabs/Nature Kit/tree_oak_dark",
        "Prefabs/Nature Kit/tree_oak_fall",
        "Prefabs/Nature Kit/tree_oak",
        "Prefabs/Nature Kit/tree_palm",
        "Prefabs/Nature Kit/tree_palmBend",
        "Prefabs/Nature Kit/tree_palmDetailedShort",
        "Prefabs/Nature Kit/tree_palmDetailedTall",
        "Prefabs/Nature Kit/tree_palmShort",
        "Prefabs/Nature Kit/tree_palmTall",
        "Prefabs/Nature Kit/tree_pineDefaultA",
        "Prefabs/Nature Kit/tree_pineDefaultB",
        "Prefabs/Nature Kit/tree_pineGroundA",
        "Prefabs/Nature Kit/tree_pineGroundB",
        "Prefabs/Nature Kit/tree_pineRoundA",
        "Prefabs/Nature Kit/tree_pineRoundB",
        "Prefabs/Nature Kit/tree_pineRoundC",
        "Prefabs/Nature Kit/tree_pineRoundD",
        "Prefabs/Nature Kit/tree_pineRoundE",
        "Prefabs/Nature Kit/tree_pineRoundF",
        "Prefabs/Nature Kit/tree_pineSmallA",
        "Prefabs/Nature Kit/tree_pineSmallB",
        "Prefabs/Nature Kit/tree_pineSmallC",
        "Prefabs/Nature Kit/tree_pineSmallD",
        "Prefabs/Nature Kit/tree_pineTallA_detailed",
        "Prefabs/Nature Kit/tree_pineTallA",
        "Prefabs/Nature Kit/tree_pineTallB_detailed",
        "Prefabs/Nature Kit/tree_pineTallB",
        "Prefabs/Nature Kit/tree_pineTallC_detailed",
        "Prefabs/Nature Kit/tree_pineTallC",
        "Prefabs/Nature Kit/tree_pineTallD_detailed",
        "Prefabs/Nature Kit/tree_pineTallD",
        "Prefabs/Nature Kit/tree_plateau_dark",
        "Prefabs/Nature Kit/tree_plateau_fall",
        "Prefabs/Nature Kit/tree_plateau",
        "Prefabs/Nature Kit/tree_simple_dark",
        "Prefabs/Nature Kit/tree_simple_fall",
        "Prefabs/Nature Kit/tree_simple",
        "Prefabs/Nature Kit/tree_small_dark",
        "Prefabs/Nature Kit/tree_small_fall",
        "Prefabs/Nature Kit/tree_small",
        "Prefabs/Nature Kit/tree_tall_dark",
        "Prefabs/Nature Kit/tree_tall_fall",
        "Prefabs/Nature Kit/tree_tall",
        "Prefabs/Nature Kit/tree_thin_dark",
        "Prefabs/Nature Kit/tree_thin_fall"
    };
    
    public static readonly string[] cactiPaths = {
        "Prefabs/Nature Kit/cactus_tall",
        "Prefabs/Nature Kit/cactus_short"
    };

    public static readonly string[] rockPaths = {
        "Prefabs/Nature Kit/stone_largeA",
        "Prefabs/Nature Kit/stone_largeB",
        "Prefabs/Nature Kit/stone_largeC",
        "Prefabs/Nature Kit/stone_largeD",
        "Prefabs/Nature Kit/stone_largeE",
        "Prefabs/Nature Kit/stone_largeF",
        "Prefabs/Nature Kit/stone_smallA",
        "Prefabs/Nature Kit/stone_smallB",
        "Prefabs/Nature Kit/stone_smallC",
        "Prefabs/Nature Kit/stone_smallD",
        "Prefabs/Nature Kit/stone_smallE",
        "Prefabs/Nature Kit/stone_smallF",
        "Prefabs/Nature Kit/stone_smallFlatA",
        "Prefabs/Nature Kit/stone_smallFlatB",
        "Prefabs/Nature Kit/stone_smallFlatC",
        "Prefabs/Nature Kit/stone_smallG",
        "Prefabs/Nature Kit/stone_smallH",
        "Prefabs/Nature Kit/stone_smallI",
        "Prefabs/Nature Kit/stone_smallTopA",
        "Prefabs/Nature Kit/stone_smallTopB",
        "Prefabs/Nature Kit/stone_tallA",
        "Prefabs/Nature Kit/stone_tallB",
        "Prefabs/Nature Kit/stone_tallC",
        "Prefabs/Nature Kit/stone_tallD",
        "Prefabs/Nature Kit/stone_tallE",
        "Prefabs/Nature Kit/stone_tallF",
        "Prefabs/Nature Kit/stone_tallG",
        "Prefabs/Nature Kit/stone_tallH",
        "Prefabs/Nature Kit/stone_tallI",
        "Prefabs/Nature Kit/stone_tallJ"
    };
}
